version: "3.7"
services:
  backend:
    image: kazuman/simple-server:latest
  nginx:
    image: nginx:latest
    volumes:
      - "/d/project/breaker/conf.d:/etc/nginx/conf.d"
      - "/d/project/breaker/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
